version: "3"
services:

  scrapy:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./:/code
      - ./secrets:/mnt/secrets
    depends_on:
      - memcached
    command: ["python", "run.py"]

  memcached:
    image: memcached:1.5.8-alpine
